// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: The Protobuf Project - Open Source 2026
// source: {{ .SourcePath }}
{{ range $svcName, $methods := .Services }}
#[cxx::bridge(namespace = "{{ $.CppNamespace }}")]
mod ffi_{{ $svcName | snakeCase }} {
    unsafe extern "C++" {
        include!("{{ $.IncludePath }}");

        type {{ $svcName }}McpImpl;
{{- range $methName, $info := $methods }}
        fn {{ $info.CppMethodName }}(self: &{{ $svcName }}McpImpl, args_json: &str) -> String;
{{- end }}

        fn new_{{ $svcName | snakeCase }}_mcp() -> UniquePtr<{{ $svcName }}McpImpl>;
    }

    extern "Rust" {
        fn start_{{ $svcName | snakeCase }}_mcp_http(host: &str, port: u16, base_path: &str);
        fn start_{{ $svcName | snakeCase }}_mcp_stdio();
    }
}
{{ end }}
pub mod mcp_handler;
{{ range $svcName, $methods := .Services }}
fn start_{{ $svcName | snakeCase }}_mcp_http(host: &str, port: u16, base_path: &str) {
    let rt = tokio::runtime::Runtime::new().expect("failed to create tokio runtime");
    rt.block_on(async {
        if let Err(e) = mcp_handler::serve_{{ $svcName | snakeCase }}_mcp(host, port, base_path).await {
            eprintln!("MCP HTTP server failed: {e}");
            eprintln!("Hint: Port {port} may be in use. Try MCP_PORT=8083 ./server or kill the process using the port.");
            std::process::exit(1);
        }
    });
}

fn start_{{ $svcName | snakeCase }}_mcp_stdio() {
    let rt = tokio::runtime::Runtime::new().expect("failed to create tokio runtime");
    rt.block_on(async {
        mcp_handler::serve_{{ $svcName | snakeCase }}_mcp_stdio()
            .await
            .expect("MCP stdio server failed");
    });
}
{{ end }}
