// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: The Protobuf Project - Open Source 2026
// source: {{ .SourcePath }}

#include "{{ .IncludePath }}"

#include <grpcpp/grpcpp.h>
#include <google/protobuf/util/json_util.h>

{{ .NamespaceOpen }}

static std::string _mcp_error_json(const std::string& msg) {
    std::string escaped;
    escaped.reserve(msg.size());
    for (char c : msg) {
        if (c == '"') escaped += "\\\"";
        else if (c == '\\') escaped += "\\\\";
        else if (c == '\n') escaped += "\\n";
        else escaped += c;
    }
    return "{\"error\":\"" + escaped + "\"}";
}

[[maybe_unused]] static std::string _mcp_msg_to_json(const ::google::protobuf::Message& msg) {
    std::string json;
    ::google::protobuf::util::JsonPrintOptions opts;
    opts.preserve_proto_field_names = true;
    auto st = ::google::protobuf::util::MessageToJsonString(msg, &json, opts);
    if (!st.ok()) return _mcp_error_json(std::string(st.message()));
    return json;
}
{{ range $svcName, $methods := .Services }}
{{ $svcName }}McpImpl::{{ $svcName }}McpImpl(std::shared_ptr<{{ $svcName }}::Stub> stub)
    : stub_(std::move(stub)) {}
{{ range $methName, $info := $methods }}
rust::String {{ $svcName }}McpImpl::{{ $info.CppMethodName }}(rust::Str args_json) const {
    std::string json(args_json.data(), args_json.size());
    {{ $info.InputType }} req;
    auto parse_st = ::google::protobuf::util::JsonStringToMessage(json, &req);
    if (!parse_st.ok())
        return rust::String(_mcp_error_json(std::string(parse_st.message())));
    ::grpc::ClientContext ctx;
    {{ $info.OutputType }} resp;
    auto st = stub_->{{ $info.GoName }}(&ctx, req, &resp);
    if (!st.ok())
        return rust::String(_mcp_error_json(st.error_message()));
    return rust::String(_mcp_msg_to_json(resp));
}
{{ end }}
std::unique_ptr<{{ $svcName }}McpImpl> new_{{ $svcName | snakeCase }}_mcp() {
    auto channel = ::grpc::CreateChannel(
        "localhost:50051", ::grpc::InsecureChannelCredentials());
    auto stub = {{ $svcName }}::NewStub(channel);
    return std::make_unique<{{ $svcName }}McpImpl>(std::move(stub));
}
{{ end }}
{{ .NamespaceClose }}
