// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: The Protobuf Project - Open Source 2026
// source: {{ .SourcePath }}

#pragma once

#include <memory>
#include <string>
#include "rust/cxx.h"
#include "{{ .GrpcInclude }}"

{{ .NamespaceOpen }}
{{ range $svcName, $methods := .Services }}
class {{ $svcName }}McpImpl {
public:
    explicit {{ $svcName }}McpImpl(std::shared_ptr<{{ $svcName }}::Stub> stub);
{{- range $methName, $info := $methods }}
    rust::String {{ $info.CppMethodName }}(rust::Str args_json) const;
{{- end }}

private:
    std::shared_ptr<{{ $svcName }}::Stub> stub_;
};

std::unique_ptr<{{ $svcName }}McpImpl> new_{{ $svcName | snakeCase }}_mcp();
{{ end }}
{{ .NamespaceClose }}
