# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/protobuf/annotations.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mcp/protobuf/annotations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from mcp.protobuf import service_options_pb2 as mcp_dot_protobuf_dot_service__options__pb2
from mcp.protobuf import prompt_pb2 as mcp_dot_protobuf_dot_prompt__pb2
from mcp.protobuf import elicitation_pb2 as mcp_dot_protobuf_dot_elicitation__pb2
from mcp.protobuf import field_pb2 as mcp_dot_protobuf_dot_field__pb2
from mcp.protobuf import enum_pb2 as mcp_dot_protobuf_dot_enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emcp/protobuf/annotations.proto\x12\x0cmcp.protobuf\x1a google/protobuf/descriptor.proto\x1a\"mcp/protobuf/service_options.proto\x1a\x19mcp/protobuf/prompt.proto\x1a\x1emcp/protobuf/elicitation.proto\x1a\x18mcp/protobuf/field.proto\x1a\x17mcp/protobuf/enum.proto:_\n\x07service\x12\x1f.google.protobuf.ServiceOptions\x18\xb8\x8e\x03 \x01(\x0b\x32\x1f.mcp.protobuf.MCPServiceOptionsR\x07service\x88\x01\x01:U\n\x04tool\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\x0b\x32\x1c.mcp.protobuf.MCPToolOptionsR\x04tool\x88\x01\x01:T\n\x06prompt\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\x0b\x32\x17.mcp.protobuf.MCPPromptR\x06prompt\x88\x01\x01:c\n\x0b\x65licitation\x12\x1e.google.protobuf.MethodOptions\x18\xbb\x8e\x03 \x01(\x0b\x32\x1c.mcp.protobuf.MCPElicitationR\x0b\x65licitation\x88\x01\x01:W\n\x05\x66ield\x12\x1d.google.protobuf.FieldOptions\x18\xbc\x8e\x03 \x01(\x0b\x32\x1d.mcp.protobuf.MCPFieldOptionsR\x05\x66ield\x88\x01\x01:S\n\x04\x65num\x12\x1c.google.protobuf.EnumOptions\x18\xbd\x8e\x03 \x01(\x0b\x32\x1c.mcp.protobuf.MCPEnumOptionsR\x04\x65num\x88\x01\x01:h\n\nenum_value\x12!.google.protobuf.EnumValueOptions\x18\xbe\x8e\x03 \x01(\x0b\x32!.mcp.protobuf.MCPEnumValueOptionsR\tenumValue\x88\x01\x01\x42k\n\x10\x63om.mcp.protobufB\x10\x41nnotationsProtoP\x01ZCgithub.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.protobuf.annotations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.mcp.protobufB\020AnnotationsProtoP\001ZCgithub.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppb'
# @@protoc_insertion_point(module_scope)
