# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/protobuf/elicitation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mcp/protobuf/elicitation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emcp/protobuf/elicitation.proto\x12\x0cmcp.protobuf\"B\n\x0eMCPElicitation\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x16\n\x06schema\x18\x02 \x01(\tR\x06schemaBk\n\x10\x63om.mcp.protobufB\x10\x45licitationProtoP\x01ZCgithub.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.protobuf.elicitation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.mcp.protobufB\020ElicitationProtoP\001ZCgithub.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppb'
  _globals['_MCPELICITATION']._serialized_start=48
  _globals['_MCPELICITATION']._serialized_end=114
# @@protoc_insertion_point(module_scope)
