# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/protobuf/enum.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'mcp/protobuf/enum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17mcp/protobuf/enum.proto\x12\x0cmcp.protobuf\"2\n\x0eMCPEnumOptions\x12 \n\x0b\x64\x65scription\x18\x01 \x01(\tR\x0b\x64\x65scription\"7\n\x13MCPEnumValueOptions\x12 \n\x0b\x64\x65scription\x18\x01 \x01(\tR\x0b\x64\x65scriptionB_\n\x10\x63om.mcp.protobufB\tEnumProtoP\x01Z>github.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.protobuf.enum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.mcp.protobufB\tEnumProtoP\001Z>github.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppb'
  _globals['_MCPENUMOPTIONS']._serialized_start=41
  _globals['_MCPENUMOPTIONS']._serialized_end=91
  _globals['_MCPENUMVALUEOPTIONS']._serialized_start=93
  _globals['_MCPENUMVALUEOPTIONS']._serialized_end=148
# @@protoc_insertion_point(module_scope)
