# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp/protobuf/mime_type.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mcp/protobuf/mime_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmcp/protobuf/mime_type.proto\x12\x0cmcp.protobuf*\xd9\x02\n\x0bMCPMimeType\x12\x1d\n\x19MCP_MIME_TYPE_UNSPECIFIED\x10\x00\x12\"\n\x1eMCP_MIME_TYPE_APPLICATION_JSON\x10\x01\x12\x1c\n\x18MCP_MIME_TYPE_TEXT_PLAIN\x10\x02\x12\x1b\n\x17MCP_MIME_TYPE_TEXT_HTML\x10\x03\x12\x1f\n\x1bMCP_MIME_TYPE_TEXT_MARKDOWN\x10\x04\x12!\n\x1dMCP_MIME_TYPE_APPLICATION_XML\x10\x05\x12*\n&MCP_MIME_TYPE_APPLICATION_OCTET_STREAM\x10\x06\x12!\n\x1dMCP_MIME_TYPE_APPLICATION_PDF\x10\x07\x12\x1b\n\x17MCP_MIME_TYPE_IMAGE_PNG\x10\x08\x12\x1c\n\x18MCP_MIME_TYPE_IMAGE_JPEG\x10\tBh\n\x10\x63om.mcp.protobufB\rMimeTypeProtoP\x01ZCgithub.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp.protobuf.mime_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.mcp.protobufB\rMimeTypeProtoP\001ZCgithub.com/the-protobuf-project/grpc-mcp-gateway/mcp/protobuf/mcppb'
  _globals['_MCPMIMETYPE']._serialized_start=47
  _globals['_MCPMIMETYPE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
